name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Build Web Assets
        run: npm run build

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Build APK File
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Save APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: PaniMitr-App-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
